repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        exclude: (^notebooks/|^docs/)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        exclude: (^notebooks/|^docs/|setup.py)
-   repo:  https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
        -   id: flake8
            exclude: (^notebooks/|^docs/)
